ansible_user: admin
ansible_ssh_private_key_file: <PATH>
ansible_ssh_common_args: >-
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null
          -o ProxyCommand="ssh -i {{ ansible_ssh_private_key_file }} -W %h:22 bastion_host"
kubeconfig_dir: "/home/{{ ansible_user }}/.kube"
kubeconfig_path: "{{ kubeconfig_dir }}/config"
cni_version: <VERSION > ("1.3.0")
flannel_version: <VERSION> ("0.27.3")
kube_version: <VERSION> ("1.34")
helm_version: <VERSION> ("4.0.0")
cni: "flannel" ("flannel" or "calico")
pod_network_cidr: <CIDR> ("10.244.0.0/16")
postgres_username: <USERNAME>
postgres_database: <DATABASE>
aws_access_key_id: <ID>
aws_secret_access_key: <KEY>
aws_region: <REGION>
gameland_record: <RECORD>
prometheus_record: <RECORD>
grafana_record: <RECORD>
