ansible_user: admin
ansible_ssh_private_key_file: <PATH>
ansible_ssh_common_args: >-
          -o StrictHostKeyChecking=no
          -o UserKnownHostsFile=/dev/null
          -o ProxyCommand="ssh -i {{ ansible_ssh_private_key_file }} -W %h:22 bastion_host"
kubeconfig_path: "/etc/rancher/k3s/k3s.yaml"
postgres_username: <USERNAME>
postgres_database: <DATABASE>
aws_access_key_id: <ID>
aws_secret_access_key: <KEY>
aws_region: <REGION>
gameland_record: <RECORD>
prometheus_record: <RECORD>
grafana_record: <RECORD>
