apiVersion: v1
kind: Namespace
metadata:
  name: gameland
  labels:
    prometheus: enabled
---
apiVersion: v1
kind: Secret
metadata:
  name: gameland-secret
  namespace: gameland
type: Opaque
data:
  DATABASE_URL: <BASE_64_ENCODED_URL>
  NEXTAUTH_SECRET: <BASE_64_ENCODED_SECRET>
  GMAIL_USER: <BASE_64_ENCODED_USER>
  GMAIL_APP_PASSWORD: <BASE_64_ENCODED_PASSWORD>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gameland
  namespace: gameland
  labels:
    app: gameland
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gameland
  template:
    metadata:
      labels:
        app: gameland
    spec:
      nodeSelector:
        role: worker-app
      containers:
        - name: gameland
          image: arailler/gameland:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: gameland-secret
                  key: DATABASE_URL
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: gameland-secret
                  key: NEXTAUTH_SECRET
            - name: GMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: gameland-secret
                  key: GMAIL_USER
            - name: GMAIL_APP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: gameland-secret
                  key: GMAIL_APP_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: gameland
  namespace: gameland
spec:
  selector:
    app: gameland
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gameland-hpa
  namespace: gameland
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gameland
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
